Description: "Creates a Linux operator machine."
Mappings:
  Images:
    us-east-1:
      Id: "ami-007855ac798b5175e"
    us-east-2:
      Id: "ami-0a695f0d95cefc163"
    us-west-1:
      Id: "ami-014d05e6b24240371"
    us-west-2:
      Id: "ami-0fcf52bcf5db7b003"
Resources:
  OperatorInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
        - Images
        - !Ref AWS::Region
        - Id
      InstanceType: "t3.large"
      KeyName: !Sub "tanzu-operations-${AWS::Region}"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            DeleteOnTermination: true
      SecurityGroupIds:
        - !Sub "tanzu-operations-${AWS::Region}"
      Tags:
        - Key: "Name"
          Value: !Sub "tanzu-operations-${AWS::Region}"
Outputs:
  InstanceId:
    Value: !Ref OperatorInstance
  PublicDnsName:
    Value: !GetAtt OperatorInstance.PublicDnsName
